import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SocketProvider } from "@/context/SocketContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="flex">
        <Navbar />
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  );
}
